# Usa una imagen base oficial de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Expone el puerto en el que la aplicación se ejecutará
EXPOSE 3000

# docker build -f Dockerfile.dev -t frontend-app-dev .

# docker run -d --name frontend-dev -p 3000:3000 -v $(pwd):/app -v /app/node_modules frontend-app-dev
