name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout de la rama develop
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Obtiene todo el historial

      # Paso 2: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 3: Construir y exportar el sitio estático
      - name: Build and export static site
        run: npm run build

      # Paso 4: Desplegar a la rama main
      - name: Deploy to main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: main
          # Opcional: Forzar un commit huérfano para evitar conflictos
          force_orphan: true
