name: Deploy to GitHub Pages

# Ejecuta este workflow en cada push a la rama develop
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código en la rama develop
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Asegura que se obtengan todas las ramas y el historial completo

      # Paso 2: Instalar las dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # Paso 3: Construir y exportar el proyecto (Next.js con output: "export")
      - name: Build and export static site
        run: npm run build

      # Paso 4: Depuración: listar archivos generados
      - name: List generated files
        run: ls -R ./out

      # Paso 5: Hacer checkout de la rama main
      - name: Checkout main branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout main

      # Paso 6: Limpiar archivos excepto .git y .github
      - name: Clean current directory except .git and .github
        run: |
          find . -mindepth 1 -not -name '.git' -not -name '.github' -delete

      # Paso 7: Copiar los archivos exportados al directorio actual
      - name: Copy output to main branch
        run: cp -r ./out/* ./

      # Paso 8: Commit y push a la rama main usando GITHUB_TOKEN
      - name: Commit and push to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Deploy static site from develop"
          git push origin main